import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.css'
import Header from '@/components/header/Header'
import PersonalInfo from '@/components/personalInfo/PersonalInfo'
import Footer from '@/components/footer/Footer'
import CallToAction from '@/components/callToAction/CallToAction'
import Carousel from '@/components/carousel/Carousel'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
   return (
      <>
         <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <main className="vh-100 w-100">
            <Header></Header>
            <PersonalInfo></PersonalInfo>
            <Carousel></Carousel>
            <CallToAction></CallToAction>
            <Footer></Footer>
         </main>
      </>
   )
}
